feat: link icon
palmetto/palmetto-design-tokens pull request #167
Opened 2021-09-14 22:03 UTC by osbornedesign

2021-09-14 22:08 UTC, nathanyoung requested changes

2021-09-14 22:08 UTC, nathanyoung commented on icons/link.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="16" width="16" viewBox="0 0 16 16"><title>link</title><g fill="currentColor" class="nc-icon-wrapper"><path data-color="color-2" d="M4.5,16c-1.2,0-2.3-0
remove `class="nc-icon-wrapper"`

2021-09-14 22:09 UTC, nathanyoung commented
can you include a screenshot of the icon?

2021-09-15 12:56 UTC, osbornedesign reviewed
removed `class="nc-icon-wrapper"`

![image](https://user-images.githubusercontent.com/15643874/133437256-05557cfb-76f1-4321-bdfc-878d1eeddb96.png)

2021-09-15 16:58 UTC, nathanyoung approved these changes

2021-09-15 16:59 UTC, merged